# Note: Setting this to `required` will add 20-50s to CI image boot time
sudo: false
dist: trusty
services:
  - docker
language: generic
notifications:
  email:
    recipients:

install:
    # Pull in MoveIt's ROS Docker CI image (piping to `/dev/null` to hide output)
    - DOCKER_IMAGE=moveit/moveit:$ROS_DISTRO-ci
    - echo "Pulling in Docker Image \"$DOCKER_IMAGE\""
    - docker pull $DOCKER_IMAGE > /dev/null

    # Run the CI script inside the docker container
    - docker run 
      --env $REPOSITORY_NAME
      --env $RUN_BUILD
      --env $RUN_TESTS 
      --env $RUN_FORMATTING_CHECKS
      --env $TRAVIS_PULL_REQUEST
      --env $TRAVIS_BRANCH
      --volume $(pwd):/root/$REPOSITORY_NAME
      $DOCKER_IMAGE
      /bin/bash -c "/root/$REPOSITORY_NAME/travis_ci.sh"

env:
  # Global Variables that are set at the start of every CI run
  global:
    # Get the name of this repository from the `TRAVIS_REPO_SLUG`
    # ex. "UBC-Snowbots/Snowflake" would give "Snowflake"
    - REPOSITORY_NAME=$(basename $TRAVIS_REPO_SLUG)
    # Set the ROS Distro we're using (determines what Docker container we use)
    - ROS_DISTRO=kinetic 
    # Set variables selecting tests to default values
    # (if they are not given one it causes issues with the `--env` flag for `docker run`)
    - RUN_BUILD=""
    - RUN_TESTS=""
    - RUN_FORMATTING_CHECKS=""

  # Each entry here represents a different CI run
  # The variables here are uniquely set at the start of each different test
  matrix:
  # Test building the repo and running tests
    # NOTE: this is a single test
    - RUN_BUILD="true"
      RUN_TESTS="true"
    # Test Formatting
    - RUN_FORMATTING_CHECKS="true"
