# Note: Setting this to `required` will add 20-50s to CI image boot time
sudo: false
dist: trusty
services:
  - docker
language: generic
notifications:
  email:
    recipients:

# Global Variables


install:
    # Pull in MoveIt's ROS Docker CI image (piping to `/dev/null` to hide output)
    - DOCKER_IMAGE=moveit/moveit:$ROS_DISTRO-ci
    - echo "==========================================================="
    - echo "Pulling in Docker Image \"$DOCKER_IMAGE\""
    - echo "==========================================================="
    - docker pull $DOCKER_IMAGE > /dev/null
    # Setup up the Docker image 
    - echo "==========================================================="
    - echo " Setting up the Docker Image and Installing Dependencies"
    - echo "==========================================================="
    - docker run -e $REPOSITORY_NAME /bin/bash -c "cd /root/$REPOSITORY_NAME; ./setup_scripts/install_dependencies.sh"

env:
  matrix:
    - ROS_DISTRO=kinetic 
      ROS_REPO=ros 
      UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/UBC-Snowbots/Snowflake/$TRAVIS_BRANCH/.rosinstall
#- ROS_DISTRO=kinetic 
#- UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/UBC-Snowbots/Snowflake/$TRAVIS_BRANCH/.rosinstall
#- TEST_CLANG_FORMAT=TRUE 
#- ROS_DISTRO=kinetic 
#- UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/UBC-Snowbots/Snowflake/$TRAVIS_BRANCH/.rosinstall
