sudo: required
cache: 
        - apt
language: generic
os: linux
dist: bionic

install:
        - cd $TRAVIS_BUILD_DIR
        - echo "$(pwd)"
        - ./setup_scripts/install_dependencies.sh

script:
        - source /opt/ros/melodic/setup.bash
        - catkin_make
        - catkin_make run_tests && catkin_test_results --verbose
        - ./travis_ci.sh
